create table Person(
                       id int generated always as identity primary key,
                       username varchar(30) check(length(username)>2) not null,
                       role varchar(30) not null,
                       password varchar(30)

);

alter table Person alter column password type varchar(255);

create table Book(
    id int generated by default as identity,
    title varchar(255) not null,
    publish_year int,
    content bytea
);

alter table Book add primary key (id);
